/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'title' : string,
  'content' : string,
  'chain' : string,
}
export interface Project {
  'riskExplanation' : string,
  'chain' : string,
  'name' : string,
  'liquidity' : bigint,
  'description' : string,
  'volume' : bigint,
  'lessons' : Array<Lesson>,
  'auditPresence' : boolean,
  'teamTransparency' : boolean,
  'launchDate' : bigint,
  'riskLevel' : string,
  'videos' : Array<Video>,
  'quizzes' : Array<Quiz>,
}
export interface ProjectAnalytics {
  'chainSelections' : bigint,
  'quizSubmits' : bigint,
  'lessonStarts' : bigint,
  'projectOpens' : bigint,
  'lessonCompletes' : bigint,
  'riskDetailsExpands' : bigint,
}
export interface Quiz {
  'question' : string,
  'chain' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'bio' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video { 'url' : string, 'title' : string, 'chain' : string }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProject' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      boolean,
      boolean,
      bigint,
      bigint,
      Array<Lesson>,
      Array<Quiz>,
      Array<Video>,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDataProviderStatus' : ActorMethod<[string], boolean>,
  'configureDataProvider' : ActorMethod<[string, string, string], undefined>,
  'fetchProjectsFromProvider' : ActorMethod<[string], string>,
  'getAnalytics' : ActorMethod<[], ProjectAnalytics>,
  'getAvailableDataProviders' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProjectById' : ActorMethod<[bigint], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeDataProvider' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAnalytics' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];