/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chain' : IDL.Text,
});
export const Quiz = IDL.Record({
  'question' : IDL.Text,
  'chain' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Video = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'chain' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectAnalytics = IDL.Record({
  'chainSelections' : IDL.Nat,
  'quizSubmits' : IDL.Nat,
  'lessonStarts' : IDL.Nat,
  'projectOpens' : IDL.Nat,
  'lessonCompletes' : IDL.Nat,
  'riskDetailsExpands' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Project = IDL.Record({
  'riskExplanation' : IDL.Text,
  'chain' : IDL.Text,
  'name' : IDL.Text,
  'liquidity' : IDL.Nat,
  'description' : IDL.Text,
  'volume' : IDL.Nat,
  'lessons' : IDL.Vec(Lesson),
  'auditPresence' : IDL.Bool,
  'teamTransparency' : IDL.Bool,
  'launchDate' : IDL.Int,
  'riskLevel' : IDL.Text,
  'videos' : IDL.Vec(Video),
  'quizzes' : IDL.Vec(Quiz),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(Lesson),
        IDL.Vec(Quiz),
        IDL.Vec(Video),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkDataProviderStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'configureDataProvider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'fetchProjectsFromProvider' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAnalytics' : IDL.Func([], [ProjectAnalytics], ['query']),
  'getAvailableDataProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeDataProvider' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnalytics' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chain' : IDL.Text,
  });
  const Quiz = IDL.Record({
    'question' : IDL.Text,
    'chain' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Video = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'chain' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectAnalytics = IDL.Record({
    'chainSelections' : IDL.Nat,
    'quizSubmits' : IDL.Nat,
    'lessonStarts' : IDL.Nat,
    'projectOpens' : IDL.Nat,
    'lessonCompletes' : IDL.Nat,
    'riskDetailsExpands' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Project = IDL.Record({
    'riskExplanation' : IDL.Text,
    'chain' : IDL.Text,
    'name' : IDL.Text,
    'liquidity' : IDL.Nat,
    'description' : IDL.Text,
    'volume' : IDL.Nat,
    'lessons' : IDL.Vec(Lesson),
    'auditPresence' : IDL.Bool,
    'teamTransparency' : IDL.Bool,
    'launchDate' : IDL.Int,
    'riskLevel' : IDL.Text,
    'videos' : IDL.Vec(Video),
    'quizzes' : IDL.Vec(Quiz),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(Lesson),
          IDL.Vec(Quiz),
          IDL.Vec(Video),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkDataProviderStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'configureDataProvider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'fetchProjectsFromProvider' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAnalytics' : IDL.Func([], [ProjectAnalytics], ['query']),
    'getAvailableDataProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeDataProvider' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnalytics' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };